### PR TITLE
Dev create initial project

### PR DESCRIPTION
**Pull request by skosman**
Created a hello world django project that contains a basic API endpoint.
- set it up that it can be run on Docker or locally
- setup github actions to run django test when code is pushed
Please note that is uses SQLite as the default database but this will have to be removed when a database is selected later.

### CODE REVIEW

**Comment by rbassot** [comment]
Looks like all works well including the containerized app - thanks for this! I have some updates to the README for Windows env setup, and I can push those to this branch if thats good with you.

**Review by rbassot — APPROVED** [review]
PR looks good.

**Comment by skosman** [comment]
> 

Yup that's good with me! Thanks for adding those

**Review by Russell-Waterhouse — APPROVED** [review]
This is awesome! I've got the branch running locally on my machine (with and without docker) and the whole thing works great. This is a great platform to build on, and I'm stoked to have it up and running this early!

**Comment by rbassot** [comment]
> > I have some updates to the README for Windows env setup, and I can push those to this branch if thats good with you.
> 
> Yup that's good with me! Thanks for adding those

Updates added.

**Pull request merged**
