### PR TITLE
Ci docker

### PR DESCRIPTION
**Pull request by kunnapool**
[Github Ticket](https://github.com/seng499-company2/back-end/issues/15)

### CODE REVIEW

**Comment by rbassot** [comment]
> For me, on `docker-compose up`, the database container starts correctly and a shell can be started which is great. Though, I am getting some errors for the Docker scheduler service, and thus my localhost:8000 cannot ping the API. Here are some errors I get:
> 
> image
> 
> Despite this Docker screen showing both services active, Port 8000 doesn't respond to any requests.
> 
> image
> 
> Let me know if you see the same issues.

I realized that this error occurs when the docker project is not built initially with the `--build` flag. With this the console errors are gone and the endpoints can be reached

**Comment by rbassot** [comment]
One extra error that was easily fixed (placing here for visibility) - Initially, the application blocked my localhost from pinging the API because the `ALLOWED_HOSTS` in `settings.py` required some form of localhost

image

By doing this the initial error was resolved.
-----------------------------------------------

Now, I am receiving a database error that explains that a relation doesn't exist. It looks like the following:
image

**Comment by rbassot** [comment]
After a simple build, the dependencies that change in the repository are shown as tracked by Git. We should update the `.gitignore` to hide data & database setup changes:

image

**Comment by kunnapool** [comment]
> For me, on `docker-compose up`, the database container starts correctly and a shell can be started which is great. Though, I am getting some errors for the Docker scheduler service, and thus my localhost:8000 cannot ping the API. Here are some errors I get:
> 
> image
> 
> Despite this Docker screen showing both services active, Port 8000 doesn't respond to any requests.
> 
> image
> 
> Let me know if you see the same issues.

Added to README

**Comment by kunnapool** [comment]
> After a simple build, the dependencies that change in the repository are shown as tracked by Git. We should update the `.gitignore` to hide data & database setup changes:
> 
> image

Updated `.gitignore`

**Comment by kunnapool** [comment]
> One extra error that was easily fixed (placing here for visibility) - Initially, the application blocked my localhost from pinging the API because the `ALLOWED_HOSTS` in `settings.py` required some form of localhost
> 
> image
> 
> By doing this the initial error was resolved.
> 
> Now, I am receiving a database error that explains that a relation doesn't exist. It looks like the following:
> 
> image

added

**Comment by kunnapool** [comment]
> Now, I am receiving a database error that explains that a relation doesn't exist. It looks like the following:
> 
> image

I don't get that error 🤔 

Screen Shot 2022-06-01 at 10 25 41 PM

**Comment by skosman** [comment]
> > Now, I am receiving a database error that explains that a relation doesn't exist. It looks like the following:
> > image
> 
> I don't get that error 🤔
> 
> Screen Shot 2022-06-01 at 10 25 41 PM

Did you run the db migrations command?  docker-compose run web python manage.py migrate
The docker terminal should say `You have ~19 unapplied migration(s)` if you haven't, that might explain that error?

**Comment by rbassot** [comment]
> docker-compose run web python manage.py migrate

Sorry about that, I mistyped the migration command initially. After rebuilding the app it all looks good, thanks

**Review by rbassot — APPROVED** [review]
All looks and works great. Thanks!

**Review by skosman — APPROVED** [review]

**Pull request merged**
